# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sleepser',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='\u5b66\u53f7')),
                ('password', models.CharField(max_length=30, verbose_name='\u5bc6\u7801')),
                ('startTime', models.DateTimeField(verbose_name='\u7761\u89c9\u5f00\u59cb\u65f6\u95f4')),
                ('endTime', models.DateTimeField(verbose_name='\u7761\u89c9\u7ed3\u675f\u65f6\u95f4')),
            ],
        ),
    ]
