# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sleepser',
            new_name='SleepUser',
        ),
    ]
