# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_auto_20171122_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepuser',
            name='endTime',
            field=models.TimeField(verbose_name='\u7761\u89c9\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='sleepuser',
            name='startTime',
            field=models.TimeField(verbose_name='\u7761\u89c9\u5f00\u59cb\u65f6\u95f4'),
        ),
    ]
